name: Semgrep Spring

on:
  push:
    branches: [ "main", "master", "develop" ]
  pull_request:
    branches: [ "main", "master", "develop" ]
  schedule:
    - cron: '41 5 * * 3'
  workflow_dispatch:

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  semgrep:
    name: Spring scan
    runs-on: ubuntu-latest

    container:
      image: semgrep/semgrep:latest

    if: github.actor != 'dependabot[bot]'

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Run Semgrep default Java rules
        run: |
          semgrep scan \
            --config auto \
            --config p/java \
            --config p/findsecbugs \
            --sarif \
            --output semgrep-spring.sarif \
            .

      - name: Upload SARIF file
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep-spring.sarif
